import { eachDayOfInterval, endOfMonth, format, getDay, startOfMonth } from 'date-fns'
import { useRef, useState } from 'react'
import { useHolidays } from '../hooks/useHolidays'
import { leaveMaps } from '../utils/leavePlans'

const names={zh:['一月','二月','三月','四月','五月','六月','七月','八月','九月','十月','十一月','十二月'],en:['January','February','March','April','May','June','July','August','September','October','November','December']}
const weekdays={zh:['日','一','二','三','四','五','六'],en:['Sun','Mon','Tue','Wed','Thu','Fri','Sat']}
const todayKey=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const dateText=(v,lang)=>{const [,m,d]=v.split('-').map(Number);return lang==='zh'?`${m}月${d}日`:`${d}/${m}`}

function Month({year,index,holidays,showPlans,leave,included,lang,onClick}){
 const start=startOfMonth(new Date(year,index,1)),days=eachDayOfInterval({start,end:endOfMonth(start)}),hk=new Set((holidays.HK||[]).map(x=>x.date)),today=todayKey(),count=days.filter(d=>hk.has(format(d,'yyyy-MM-dd'))).length
 const leadingDays=getDay(start)
 const trailingDays=42-leadingDays-days.length
 return <button className="month-card" onClick={()=>onClick(index+1)}><div className="month-card-header"><h2>{names[lang][index]}</h2>{count>0&&<span>{count} {lang==='zh'?'日假期':count===1?'holiday':'holidays'}</span>}</div><div className="weekday-row">{weekdays[lang].map(x=><span key={x}>{x}</span>)}</div><div className="month-days">{Array.from({length:leadingDays}).map((_,i)=><span className="empty-day" key={`start-${i}`}/>)}{days.map(day=>{const date=format(day,'yyyy-MM-dd'),holiday=hk.has(date),needLeave=showPlans&&leave.has(date),insidePlan=showPlans&&included.has(date),todayDate=date===today;return <span key={date} className={['day',day.getDay()===0?'sunday':'',holiday?'holiday':'',needLeave?'leave-day':'',insidePlan&&!needLeave?'included-day':'',todayDate?'today':''].filter(Boolean).join(' ')}>{format(day,'d')}</span>})}{Array.from({length:trailingDays}).map((_,i)=><span className="empty-day" key={`end-${i}`}/>)}</div></button>
}

export function MonthGrid({year,lang,theme,onYearChange,onMonthClick,onLanguageChange,onThemeChange}){
 const {holidays,loading}=useHolidays(year)
 const [showPlans,setShowPlans]=useState(false),plansRef=useRef(null)
 const {plans,leave,included}=leaveMaps(year,holidays.HK||[])
 const toggle=()=>{const next=!showPlans;setShowPlans(next);if(next)setTimeout(()=>plansRef.current?.scrollIntoView({behavior:'smooth',block:'start'}),80)}
 return <main className="calendar-page"><nav className="toolbar">{[2026,2027].map(y=><button key={y} className={`year-button${year===y?' active':''}`} onClick={()=>onYearChange(y)}>{y}</button>)}<button className="theme-toggle" onClick={onThemeChange}><span className={`switch${theme==='dark'?' on':''}`}><span/></span><span>{lang==='zh'?(theme==='dark'?'最佳觀':'淺色'):(theme==='dark'?'Dark':'Light')}</span></button><button className={`plans-toggle${showPlans?' on':''}`} onClick={toggle}><span className="plans-switch"><span/></span>{lang==='zh'?'請假攻略':'Leave plans'}</button><button className="language-button" onClick={onLanguageChange}>{lang==='zh'?'EN':'中'}</button></nav><header className="calendar-header"><h1>{year}</h1><p>{lang==='zh'?'全年總覽・香港假期實心紅圈':'Year overview · Hong Kong public holidays'}</p></header>{loading?<p className="loading">Loading…</p>:<><section className="month-grid">{Array.from({length:12},(_,i)=><Month key={i} year={year} index={i} holidays={holidays} showPlans={showPlans} leave={leave} included={included} lang={lang} onClick={onMonthClick}/>)}</section>{showPlans&&<><div className="calendar-legend"><span><i className="legend-dot holiday-dot"/>{lang==='zh'?'香港公眾假期':'HK holiday'}</span><span><i className="legend-dot leave-dot"/>{lang==='zh'?'要請假日':'Annual leave required'}</span><span><i className="legend-dot included-dot"/>{lang==='zh'?'連假已包含日（週末／紅日）':'Included day off'}</span><span><i className="legend-dot today-dot"/>{lang==='zh'?'今天':'Today'}</span></div><section className="plans-section" ref={plansRef}><h2>{year} {lang==='zh'?'最佳請假方案':'Best leave plans'}</h2><p>{lang==='zh'?'預設星期六、日及香港公眾假期為休息日：金色虛線代表需要請年假的工作日；青綠色虛線代表該連假已包含的週末或公眾假期。':'Weekends and HK public holidays are days off. Gold dashed = annual leave required; teal dashed = included weekend/public holiday.'}</p><div className="plans-list">{plans.map((plan,i)=><article className="plan-item" key={plan.id}><b className="plan-code">{String.fromCharCode(65+i)}</b><div><strong>{plan.holidayLabels.join('＋')}</strong><span>{dateText(plan.start,lang)}–{dateText(plan.end,lang)} · {lang==='zh'?`連休 ${plan.totalDays} 日，請 ${plan.leaveDays} 日`:`${plan.totalDays} days off, take ${plan.leaveDays}`}</span><small>{lang==='zh'?'要請假：':'Take leave: '}{plan.leaveDates.map(d=>dateText(d,lang)).join(lang==='zh'?'、':', ')}</small></div></article>)}</div></section></>}</>}</main>
}
